on: push
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x, 1.18.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    services:
      ceph:
        image: bancek/ceph-rgw-swift-test:0.1.0-nautilus
        ports:
          - "8080:8080"
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      run: go get ./...
    - name: Wait for Ceph
      run: |
        while ! curl --fail -H "X-Auth-User: test:test" -H "X-Auth-Key: test" http://localhost:8080/auth/v1.0 2> /dev/null; do
          echo "waiting for swift"
          sleep 1
        done
        echo
    - name: Test
      run: |
        go test ./...
